disabled_rules: # rules that should not be included
    - trailing_whitespace
    - line_length
    - identifier_name
    - function_body_length
    - cyclomatic_complexity
    - function_parameter_count
    - large_tuple
    - file_length
    - type_body_length
    - multiple_closures_with_trailing_closure
included: # paths to include during linting
    - weatherapp
    - WeatherCore
    - Model
    - API
excluded: # paths to ignore during linting
    - Carthage
    - Pods
    - weatherappTests
    - weatherappUITests
# Custom configuration for rules
line_length: 120
type_body_length:
    - 300 # warning
    - 400 # error
